'use client'
import { useEffect, useState } from 'react'
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs'

export type LangCode = 'en' | 'fr' | 'ar'
export const ar: Record<string, any> = {
  status: {
    blank: 'فارغ',
    active: 'فعالة',
    redeemed: 'مستعملة',
    expired: 'منتهية',
    void: 'ملغاة',
  },
}
export const en: Record<string, any> = {
  status: {
    blank: 'Blank',
    active: 'Active',
    redeemed: 'Redeemed',
    expired: 'Expired',
    void: 'Cancelled',
  },
}


export const fr: Record<string, any> = {
  status: {
    blank: 'Vide',
    active: 'Actif',
    redeemed: 'Utilisé',
    expired: 'Expiré',
    void: 'Annulé',
  },
}
const translations: Record<LangCode, Record<string, string>> = {

  en: {
    preferences: 'Preferences',
    accountSettings: 'Account Settings',
    dashboard: 'Home',
    vouchers: 'Vouchers',
    clients: 'Clients',
    settings: 'Settings',
    logout: 'Logout',
    back: 'Back',
    home: 'Home',
    voucherDetails: 'Voucher Details',
    buyerName: 'Buyer Name',
    toWhom: 'To Whom?',
    buyerPhone: 'Buyer Phone',
    amount: 'Amount (DZD)',
    invalidPhone: 'Invalid phone number',
    existingClient: 'Existing client ✓',
    enterNameAndAmount: 'Please enter buyer name and amount.',
    invalidPhoneFormat: 'Invalid phone number format.',
    saving: 'Saving…',
    activateVoucher: 'Activate Voucher',
    consumePartial: 'Consume Partial',
    consumeAll: 'Consume All',
    close: 'Close',
    buyer: 'Buyer',
    phone: 'Phone',
    toWhomLabel: 'To Whom',
    initial: 'Initial',
    balance: 'Balance',
    created: 'Created',
    fullyConsumed: 'Voucher fully consumed.',
    consumed: 'consumed',
    remaining: 'Remaining',
    search: 'Search',
    date: 'Date',
    newestFirst: 'Newest first',
    oldestFirst: 'Oldest first',
    statuss: 'Status',
    store: 'Store',
    recipient: 'Recipient',
    all: 'All',
    blank: 'Blank',
    active: 'Active',
    redeemed: 'Redeemed',
    expired: 'Expired',
    void: 'Void',
    loadingVouchers: 'Loading vouchers...',
    noVouchers: 'No vouchers found.',
    createBlankVouchers: 'Create Blank Vouchers',
    howMany: 'How many?',
    createVouchers: 'Create Vouchers',
    creating: 'Creating…',
    noResults: 'No results',
    eachVoucherHint: 'Each voucher will be assigned a unique QR code automatically.',
    prev: 'Prev',
    next: 'Next',
    pageOf: 'Page {{page}} of {{total}}',
    loadingDashboard: 'Loading store dashboard…',
    voucherOverview: 'Voucher Overview',
    financialSummary: 'Financial Summary',
    clientOverview: 'Client Overview',
    total: 'Total',
    totalValue: 'Total Value',
    redeemedValue: 'Redeemed Value',
    totalClients: 'Total Clients',
    seeAll: 'See all',
    searchPlaceholder: 'Search by name or address...',
    sort: 'Sort',
    open: 'Open',
    closed: 'Closed',
    wilaya: 'Wilaya',
    allWilayas: 'All wilayas',
    loadingStores: 'Loading stores...',
    noStores: 'No stores found.',
    name: 'Name',
    address: 'Address',
    actions: 'Actions',
    view: 'View',
    addStoreTitle: 'Add New Store',
    addStoreDesc: 'Fill in the store details below.',
    cancel: 'Cancel',
    addStore: 'Add Store',
    storeName: 'Store name *',
    email: 'Email *',
    wilayaRange: 'Wilaya (1–58)',
    unnamed: 'Unnamed',
    noAddress: 'No address',
    none: '—',
    profile: 'Profile',
    password: 'Password',
    language: 'Language',
    roles: 'Roles',
    darkMode: 'Dark Mode',
    save: 'Save',
    confirm: 'Confirm',
    chooseLang: 'Choose your preferred language:',
    managePref: 'Manage your profile and preferences',
    stores: 'Stores',
    users: 'Users',
    totalRegistered: 'Total registered',
    allVouchers: 'All vouchers',
    currentlyActive: 'Currently active',
    usedVouchers: 'Used vouchers',
    latestStores: 'Latest Stores',
    recentVouchers: 'Recent Vouchers',
    topStores: 'Top Performing Stores',
    noActiveVouchers: 'No active vouchers found.',
    viewAll: 'View all',
    searchVouchers: 'Search vouchers by code or buyer…',
    noVouchersFound: 'No vouchers found.',
    code: 'Code',
    page: 'Page',
    of: 'of',
    numberToCreate: 'Number to create',
    create: 'Create',
    errorCreatingVouchers: 'Error creating vouchers',
    vouchersCreated: 'vouchers created successfully',
    offers: 'Offers & Packs',
    accounting: 'Accounting',
    totalRevenue: 'Total Revenue',
    subscription: 'Subscription',
    buyPacks: 'Buy Packs',
    planInfo: 'Your Current Plan',
  },
  fr: {
    preferences: 'Préférences',
    accountSettings: 'Paramètres du compte',
    voucherDetails: 'Détails du bon',
    buyerName: 'Nom de l’acheteur',
    toWhom: 'À qui ?',
    buyerPhone: 'Téléphone de l’acheteur',
    amount: 'Montant (DZD)',
    invalidPhone: 'Numéro de téléphone invalide',
    existingClient: 'Client existant ✓',
    enterNameAndAmount: 'Veuillez entrer le nom et le montant.',
    invalidPhoneFormat: 'Format du numéro invalide.',
    saving: 'Enregistrement…',
    activateVoucher: 'Activer le bon',
    consumePartial: 'Consommer partiellement',
    consumeAll: 'Tout consommer',
    close: 'Fermer',
    buyer: 'Acheteur',
    phone: 'Téléphone',
    toWhomLabel: 'À qui',
    initial: 'Montant initial',
    balance: 'Solde',
    created: 'Créé',
    fullyConsumed: 'Bon entièrement utilisé.',
    consumed: 'consommé',
    remaining: 'Restant',
    vouchers: 'Bons',
    search: 'Rechercher',
    date: 'Date',
    newestFirst: 'Les plus récents',
    oldestFirst: 'Les plus anciens',
    statuss: 'Statut',
    store: 'Magasin',
    recipient: 'Bénéficiaire',
    all: 'Tous',
    blank: 'Vide',
    active: 'Actif',
    redeemed: 'Utilisé',
    expired: 'Expiré',
    void: 'Annulé',
    loadingVouchers: 'Chargement des bons...',
    noVouchers: 'Aucun bon trouvé.',
    createBlankVouchers: 'Créer des bons vides',
    howMany: 'Combien ?',
    createVouchers: 'Créer les bons',
    creating: 'Création…',
    noResults: 'Aucun résultat',
    eachVoucherHint: 'Chaque bon aura un code QR unique automatiquement.',
    prev: 'Précédent',
    next: 'Suivant',
    pageOf: 'Page {{page}} sur {{total}}',
    loadingDashboard: 'Chargement du tableau de bord du magasin…',
    voucherOverview: 'Aperçu des bons',
    financialSummary: 'Résumé financier',
    clientOverview: 'Aperçu des clients',
    total: 'Total',

    totalValue: 'Valeur totale',
    redeemedValue: 'Valeur utilisée',
    totalClients: 'Clients totaux',
    seeAll: 'Voir tout',
    searchVouchers: 'Rechercher un bon par code ou acheteur…',
    noVouchersFound: 'Aucun bon trouvé.',
    code: 'Code',

    page: 'Page',
    of: 'sur',
    numberToCreate: 'Nombre à créer',
    create: 'Créer',
    errorCreatingVouchers: 'Erreur lors de la création des bons',
    vouchersCreated: 'bons créés avec succès',

    searchPlaceholder: 'Rechercher par nom ou adresse...',
    sort: 'Trier',
    open: 'Ouvert',
    closed: 'Fermé',
    wilaya: 'Wilaya',
    allWilayas: 'Toutes les wilayas',
    loadingStores: 'Chargement des magasins...',
    noStores: 'Aucun magasin trouvé.',
    name: 'Nom',
    address: 'Adresse',
    actions: 'Actions',
    view: 'Voir',
    addStoreTitle: 'Ajouter un magasin',
    addStoreDesc: 'Remplissez les informations du magasin ci-dessous.',
    cancel: 'Annuler',
    addStore: 'Ajouter',
    storeName: 'Nom du magasin *',
    email: 'Email *',
    wilayaRange: 'Wilaya (1–58)',
    unnamed: 'Sans nom',
    noAddress: 'Pas d’adresse',
    none: '—',
    dashboard: 'Home',
    clients: 'Clients',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    back: 'Retour',
    home: 'Accueil',
    viewAll: 'Voir tout',
    profile: 'Profil',
    password: 'Mot de passe',
    language: 'Langue',
    roles: 'Rôles',
    darkMode: 'Mode sombre',
    save: 'Enregistrer',
    confirm: 'Confirmer',
    chooseLang: 'Choisissez votre langue préférée :',
    managePref: 'Gérez votre profil et vos préférences',
    stores: 'Magasins',
    users: 'Utilisateurs',
    totalRegistered: 'Nombre total',
    allVouchers: 'Tous les bons',

    currentlyActive: 'Actuellement actifs',
    usedVouchers: 'Bons utilisés',
    latestStores: 'Derniers magasins',
    recentVouchers: 'Bons récents',
    topStores: 'Magasins les plus performants',
    noActiveVouchers: 'Aucun bon actif trouvé.',
    offers: 'Offres & Packs',
    accounting: 'Comptabilité',
    totalRevenue: 'Revenu Total',
    subscription: 'Abonnement',
    buyPacks: 'Acheter des Packs',
    planInfo: 'Votre Plan Actuel',
  },

  ar: {
    preferences: 'التفضيلات',
    accountSettings: 'إعدادات الحساب',
    dashboard: 'الرئيسية',
    vouchers: 'القسائم',
    clients: 'العملاء',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    back: 'رجوع',
    home: 'الرئيسية',
    voucherDetails: 'تفاصيل القسيمة',
    buyerName: 'اسم المشتري',
    toWhom: 'إلى من',
    buyerPhone: 'رقم المشتري',
    amount: 'المبلغ (دج)',
    invalidPhone: 'رقم الهاتف غير صالح',
    existingClient: 'عميل موجود ✓',
    enterNameAndAmount: 'يرجى إدخال اسم المشتري والمبلغ.',
    invalidPhoneFormat: 'صيغة رقم الهاتف غير صالحة.',
    saving: 'جارٍ الحفظ…',
    activateVoucher: 'تفعيل القسيمة',
    consumePartial: 'خصم جزئي',
    consumeAll: 'خصم الكل',
    close: 'إغلاق',
    buyer: 'المشتري',
    phone: 'الهاتف',
    toWhomLabel: 'إلى من',
    initial: 'المبلغ الأولي',
    balance: 'الرصيد',
    created: 'تاريخ الإنشاء',
    fullyConsumed: 'تم استهلاك القسيمة بالكامل.',
    consumed: 'تم خصمه',
    remaining: 'المتبقي',


    search: 'بحث',
    date: 'التاريخ',
    newestFirst: 'الأحدث أولاً',
    oldestFirst: 'الأقدم أولاً',
    statuss: 'الحالة',
    store: 'المتجر',
    recipient: 'المستفيد',
    all: 'الكل',
    blank: 'فارغة',
    active: 'نشطة',
    redeemed: 'مستعملة',
    expired: 'منتهية الصلاحية',
    void: 'ملغاة',
    loadingVouchers: 'جارٍ تحميل القسائم...',
    noVouchers: 'لا توجد قسائم.',
    createBlankVouchers: 'إنشاء قسائم فارغة',
    howMany: 'كم عددها؟',
    createVouchers: 'إنشاء القسائم',
    creating: 'جاري الإنشاء…',
    noResults: 'لا توجد نتائج',
    eachVoucherHint: 'سيتم تعيين رمز QR فريد لكل قسيمة تلقائيًا.',
    prev: 'السابق',
    next: 'التالي',
    pageOf: 'الصفحة {{page}} من {{total}}',
    loadingDashboard: 'جارٍ تحميل لوحة تحكم المتجر…',
    voucherOverview: 'نظرة عامة على القسائم',
    financialSummary: 'الملخص المالي',
    clientOverview: 'نظرة عامة على العملاء',
    total: 'الإجمالي',

    totalValue: 'القيمة الإجمالية',
    redeemedValue: 'القيمة المستعملة',
    totalClients: 'إجمالي العملاء',
    seeAll: 'عرض الكل',
    searchVouchers: 'ابحث عن قسيمة بواسطة الرمز أو اسم المشتري…',
    noVouchersFound: 'لم يتم العثور على قسائم.',
    code: 'الرمز',

    page: 'صفحة',
    of: 'من',
    numberToCreate: 'عدد القسائم المراد إنشاؤها',
    create: 'إنشاء',
    errorCreatingVouchers: 'حدث خطأ أثناء إنشاء القسائم',
    vouchersCreated: 'تم إنشاء القسائم بنجاح',
    viewAll: 'عرض الكل',
    profile: 'الملف الشخصي',
    password: 'كلمة المرور',
    language: 'اللغة',
    roles: 'الأدوار',
    darkMode: 'الوضع الليلي',
    save: 'حفظ',
    confirm: 'تأكيد',
    cancel: 'إلغاء',
    chooseLang: 'اختر لغتك المفضلة:',
    managePref: 'قم بإدارة ملفك وإعداداتك الشخصية',
    stores: 'المتاجر',
    users: 'المستخدمون',
    totalRegistered: 'إجمالي المسجلين',
    allVouchers: 'كل القسائم',
    currentlyActive: 'نشطة حاليًا',
    usedVouchers: 'قسائم مستخدمة',
    latestStores: 'أحدث المتاجر',
    recentVouchers: 'القسائم الحديثة',
    topStores: 'أفضل المتاجر أداءً',
    noStores: 'لا توجد متاجر بعد.',
    noActiveVouchers: 'لم يتم العثور على قسائم نشطة.',
    offers: 'العروض والباقات',
    accounting: 'المحاسبة',
    totalRevenue: 'إجمالي الإيرادات',
    searchPlaceholder: 'ابحث بالاسم أو العنوان...',
    sort: 'ترتيب',

    open: 'مفتوح',
    closed: 'مغلق',
    wilaya: 'الولاية',
    allWilayas: 'كل الولايات',
    loadingStores: 'جارٍ تحميل المتاجر...',
    name: 'الاسم',
    address: 'العنوان',
    actions: 'إجراءات',
    view: 'عرض',
    addStoreTitle: 'إضافة متجر جديد',
    addStoreDesc: 'املأ تفاصيل المتجر أدناه.',
    addStore: 'إضافة المتجر',
    storeName: 'اسم المتجر *',
    email: 'البريد الإلكتروني *',
    wilayaRange: 'الولاية (1–58)',
    unnamed: 'بدون اسم',
    noAddress: 'لا يوجد عنوان',
    none: '—',
    subscription: 'الاشتراك',
    buyPacks: 'شراء باقات',
    planInfo: 'خطتك الحالية',
  },
}

export function useLanguage() {
  const [lang, setLang] = useState<LangCode>('en')
  const supabase = createClientComponentClient()

  useEffect(() => {
    loadLang()
  }, [])

  async function loadLang() {
    try {
      const local = localStorage.getItem('lang') as LangCode | null
      if (local) {
        applyLang(local, false)
        return
      }
      const { data } = await supabase.auth.getUser()
      const userLang = data.user?.user_metadata?.lang as LangCode | undefined
      applyLang(userLang || 'en', false)
    } catch {
      applyLang('en', false)
    }
  }

  function applyLang(code: LangCode, shouldReload = true) {
    setLang(code)
    localStorage.setItem('lang', code)
    document.documentElement.lang = code
    document.documentElement.dir = code === 'ar' ? 'rtl' : 'ltr'

    if (shouldReload) window.location.reload() // ✅ reload page on user action
  }

  return { lang, setLang: (code: LangCode) => applyLang(code, true), t: translations[lang] }
}
